name: dvc

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: iterative/setup-dvc@v1
    - name: install dependencies
      run: |
        pip install dvc_s3 attrs
    - name: dvc commit
      run: |
        dvc push s3 --remote s3