name: dvc

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: iterative/setup-dvc@v1
    - name: install dependencies
      run: |
        pip install --upgrade pip 
        pip install --upgrade pyopenssl
        pip install dvc_s3 attrs==21.3.0
    - name: dvc commit
      run: |
        dvc push --remote s3