
name: lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:      
      PYTHONPATH: ./src/python:./test:./  
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python3.8 -m pip install --upgrade pip
        python3.8 -m pip install flake8
        
    - name: Running linter based on flake8
      run: |
        python3 -m flake8 test src